// <auto-generated />
using System;
using GrizzlyPlatform.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrizzlyPlatform.Api.Migrations
{
    [DbContext(typeof(GrizzlyDbContext))]
    [Migration("20260904192326_AddEventToGameFormSubmissions")]
    partial class AddEventToGameFormSubmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.ActiveScoutingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveMatchFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActivePitFormId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveMatchFormId");

                    b.HasIndex("ActivePitFormId");

                    b.ToTable("ActiveScoutingConfigurations");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlueAllianceKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.EventTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("EventTeams");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FormType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("GameForms");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameFormFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameFormSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameFormFieldId");

                    b.HasIndex("GameFormSubmissionId");

                    b.ToTable("GameFormAnswers");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameFormId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameFormId");

                    b.ToTable("GameFormFields");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameFormFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameFormFieldId");

                    b.ToTable("GameFormFieldOptions");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GameFormId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameFormSubmissions");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlueScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueTeam1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueTeam2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueTeam3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RedScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedTeam1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedTeam2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedTeam3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinningAlliance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlueTeam1Id");

                    b.HasIndex("BlueTeam2Id");

                    b.HasIndex("BlueTeam3Id");

                    b.HasIndex("RedTeam1Id");

                    b.HasIndex("RedTeam2Id");

                    b.HasIndex("RedTeam3Id");

                    b.HasIndex("EventId", "MatchType", "MatchNumber", "SetNumber")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.ActiveScoutingConfiguration", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.GameForm", null)
                        .WithMany()
                        .HasForeignKey("ActiveMatchFormId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GrizzlyPlatform.Api.Models.GameForm", null)
                        .WithMany()
                        .HasForeignKey("ActivePitFormId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Event", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.EventTeam", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.Event", "Event")
                        .WithMany("EventTeams")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "Team")
                        .WithMany("EventTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameForm", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.Season", "Season")
                        .WithMany("GameForms")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormAnswer", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.GameFormField", "GameFormField")
                        .WithMany()
                        .HasForeignKey("GameFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.GameFormSubmission", "GameFormSubmission")
                        .WithMany("Answers")
                        .HasForeignKey("GameFormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameFormField");

                    b.Navigation("GameFormSubmission");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormField", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.GameForm", "GameForm")
                        .WithMany("Fields")
                        .HasForeignKey("GameFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameForm");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormFieldOption", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.GameFormField", "GameFormField")
                        .WithMany("Options")
                        .HasForeignKey("GameFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameFormField");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormSubmission", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("GrizzlyPlatform.Api.Models.GameForm", "GameForm")
                        .WithMany()
                        .HasForeignKey("GameFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId");

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("GameForm");

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Match", b =>
                {
                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "BlueTeam1")
                        .WithMany()
                        .HasForeignKey("BlueTeam1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "BlueTeam2")
                        .WithMany()
                        .HasForeignKey("BlueTeam2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "BlueTeam3")
                        .WithMany()
                        .HasForeignKey("BlueTeam3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "RedTeam1")
                        .WithMany()
                        .HasForeignKey("RedTeam1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "RedTeam2")
                        .WithMany()
                        .HasForeignKey("RedTeam2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrizzlyPlatform.Api.Models.Team", "RedTeam3")
                        .WithMany()
                        .HasForeignKey("RedTeam3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlueTeam1");

                    b.Navigation("BlueTeam2");

                    b.Navigation("BlueTeam3");

                    b.Navigation("Event");

                    b.Navigation("RedTeam1");

                    b.Navigation("RedTeam2");

                    b.Navigation("RedTeam3");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Event", b =>
                {
                    b.Navigation("EventTeams");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameForm", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormField", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.GameFormSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Season", b =>
                {
                    b.Navigation("GameForms");
                });

            modelBuilder.Entity("GrizzlyPlatform.Api.Models.Team", b =>
                {
                    b.Navigation("EventTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
